
from connection import connection
def tables():
    with connection() as con:
        cur = con.cursor()
        qu1 = "create table books( book_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,title VARCHAR2(50), author VARCHAR2(50), category VARCHAR2(50), available VARCHAR2(10) DEFAULT 'Yes')"
        qu2 = "Create table members (member_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR2(50), phone VARCHAR2(15))"
        qu3 = "Create table issue (issue_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, book_id NUMBER REFERENCES books(book_id),member_id NUMBER REFERENCES members(member_id), issue_date DATE, return_date DATE)"
        cur.execute(qu1)
        cur.execute(qu2)
        cur.execute(qu3)
        
        print("Table Created")
